Feature #8 - Allow PHP8
pkly/i18next-php pull request #9
Opened 2021-01-19 10:09 UTC by leohubert

This PR close #8

2021-01-19 10:30 UTC, pkly commented
Correct me if I'm wrong but I thought that >= operator allows for PHP 8 as well?

2021-01-19 10:39 UTC, leohubert commented
I'am not sur about that. But if it is correct i don't recommend to allow php8 with that way because all dependencies may not be compatible.

It preferable to allow future php version manually after check if it work perfectly.

2021-01-24 16:36 UTC, pkly requested changes

2021-01-24 16:36 UTC, pkly commented on README.md
> +    <img src="https://github.com/leohubert/i18next-php/workflows/Tests/badge.svg">
pkly instead of leo

2021-01-24 16:36 UTC, pkly commented on composer.json
> -		"php": ">=7.3",
Please quickly check if this change was even necessary.

2021-01-24 16:36 UTC, pkly commented on composer.json
> +        "monolog/monolog": "^2.2"
Likely not a required change.

2021-01-27 08:48 UTC, leohubert commented on README.md
> +    <img src="https://github.com/leohubert/i18next-php/workflows/Tests/badge.svg">
Oh yeah of course !

2021-01-27 09:09 UTC, leohubert commented on composer.json
> +        "monolog/monolog": "^2.2"
I've changed that for multiple reasons:

- First the support of phpunit 6 was stopped since `February 1, 2019`
- `phpunit` introduce php8 support started from `8.5`  and `9.3.3`
- `monolog` introduce php8 support started from `2.2`

2021-01-27 09:16 UTC, leohubert commented on composer.json
> -		"php": ">=7.3",
It's true. That will support php7.3 and anything above or equal to 7.3.

https://getcomposer.org/doc/articles/versions.md#summary

But as I told you, i thing it's better to unlock php versions as you go along.

2021-02-01 11:08 UTC, leohubert commented on README.md
> +    <img src="https://github.com/leohubert/i18next-php/workflows/Tests/badge.svg">
Done! Ready to merge

2021-02-08 18:14 UTC, merged